services:
  jbot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    tty: true
    environment:
      API_TOKEN: ${API_TOKEN}
      CLAUDE_CONFIG_DIR: /root/.claude
    volumes:
      - ./src:/app
      - claude-code-config:/root/.claude

volumes:
  claude-code-config:

networks:
  voicevox-engine-nw:
    external: true
    name: voicevox-engine-nw